### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'span'; File "/usr/local/lib/python3.10/site-packages/pytube/parser.py"

### ISSUE THREAD

**Issue by Martouta** [Martouta/speech_processor#33]
> speech_processor_1  | 2021-12-16 15:15:32,620 - root - INFO - [1/6] Downloading multimedia from URL ... [140638112765696-1-12-16.15:15:32608107]
> speech_processor_1  | 2021-12-16 15:15:34,391 - root - ERROR - <class 'AttributeError'> : 'NoneType' object has no attribute 'span'
> speech_processor_1  |     TRACEBACK:
> speech_processor_1  |     Traceback (most recent call last):
> speech_processor_1  |   File "/usr/src/app/./app/process_resource.py", line 15, in process_resource
> speech_processor_1  |     return __process_resource(json_parsed, recognition_id)
> speech_processor_1  |   File "/usr/src/app/./app/process_resource.py", line 25, in __process_resource
> speech_processor_1  |     filepath = download_multimedia_from_url(recognition_id, json_parsed)
> speech_processor_1  |   File "/usr/src/app/./app/download_multimedia_from_url.py", line 20, in download_multimedia_from_url
> speech_processor_1  |     __download_youtube_video(json_parsed['youtube_reference_id'], fp_tuple)
> speech_processor_1  |   File "/usr/src/app/./app/download_multimedia_from_url.py", line 35, in __download_youtube_video
> speech_processor_1  |     .streams \
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/__main__.py", line 292, in streams
> speech_processor_1  |     return StreamQuery(self.fmt_streams)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/__main__.py", line 177, in fmt_streams
> speech_processor_1  |     extract.apply_signature(stream_manifest, self.vid_info, self.js)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
> speech_processor_1  |     cipher = Cipher(js=js)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/cipher.py", line 44, in __init__
> speech_processor_1  |     self.throttling_array = get_throttling_function_array(js)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/cipher.py", line 323, in get_throttling_function_array
> speech_processor_1  |     str_array = throttling_array_split(array_raw)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/parser.py", line 158, in throttling_array_split
> speech_processor_1  |     match_start, match_end = match.span()
> speech_processor_1  | AttributeError: 'NoneType' object has no attribute 'span'
> speech_processor_1  | 2021-12-16 15:15:34,391 - root - ERROR - <class 'AttributeError'> : 'NoneType' object has no attribute 'span'
> speech_processor_1  |     TRACEBACK:
> speech_processor_1  |     Traceback (most recent call last):
> speech_processor_1  |   File "/usr/src/app/./app/process_resource.py", line 15, in process_resource
> speech_processor_1  |     return __process_resource(json_parsed, recognition_id)
> speech_processor_1  |   File "/usr/src/app/./app/process_resource.py", line 25, in __process_resource
> speech_processor_1  |     filepath = download_multimedia_from_url(recognition_id, json_parsed)
> speech_processor_1  |   File "/usr/src/app/./app/download_multimedia_from_url.py", line 20, in download_multimedia_from_url
> speech_processor_1  |     __download_youtube_video(json_parsed['youtube_reference_id'], fp_tuple)
> speech_processor_1  |   File "/usr/src/app/./app/download_multimedia_from_url.py", line 35, in __download_youtube_video
> speech_processor_1  |     .streams \
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/__main__.py", line 292, in streams
> speech_processor_1  |     return StreamQuery(self.fmt_streams)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/__main__.py", line 177, in fmt_streams
> speech_processor_1  |     extract.apply_signature(stream_manifest, self.vid_info, self.js)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
> speech_processor_1  |     cipher = Cipher(js=js)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/cipher.py", line 44, in __init__
> speech_processor_1  |     self.throttling_array = get_throttling_function_array(js)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/cipher.py", line 323, in get_throttling_function_array
> speech_processor_1  |     str_array = throttling_array_split(array_raw)
> speech_processor_1  |   File "/usr/local/lib/python3.10/site-packages/pytube/parser.py", line 158, in throttling_array_split
> speech_processor_1  |     match_start, match_end = match.span()
> speech_processor_1  | AttributeError: 'NoneType' object has no attribute 'span'

**Comment by Martouta** [comment]
Closed by #32
